made index.html homepage & menuitem
nznewspapers/nznewspapers pull request #18
Opened 2021-12-05 18:25 UTC by news-papers

I made "index.html" a homepage and took out digitised from all

2021-12-05 18:26 UTC, news-papers commented
Don't know if index.html is designed to be a homepage at all but it's better then nothing

2021-12-06 03:04 UTC, nznewspapers reviewed
I think we should wait on this. I don't like saying "index.html" in a link. Let's discuss tomorrow.

2021-12-06 03:05 UTC, nznewspapers commented on docs/index.html
> +    <script src="index.js"></script>
I want to wait to make this change until I can fix the homepage.

2021-12-24 17:13 UTC, nznewspapers requested changes
We don't need this change.

2021-12-24 17:55 UTC, closed without merging